export enum CollectionNames {
  ProjectIndexes = 'projectIndexes',
  ProjectMembers = 'members',
  ProjectInvitations = 'invitations',
  UserApplications = 'applications',
  Applications = 'applications',
  Trees = 'trees',
  TreeIdentities = 'tree-identities',
  Identities = 'identities',
  Projects = 'projects',
  Statements = 'statements',
  StatementsBackers = 'statements_backers',
  Entities = 'entities',
  Users = 'users',
}
